### ISSUE TITLE
Setting LESS in the environment may cause -w mode to exit prematurely

### ISSUE THREAD

**Issue by mid-kid** [simonlindholm/asm-differ#110]
My environment sets the LESS variable, to `LESS=-RXF`.
One particular component of this, -F or --quit-if-one-screen, causes less to exit when it's not necessary to page things. I find this very useful and would like to keep it this way.
However, it completely breaks the functionality of `diff.py -w` when enabled, causing it to always exit.

Considering asm-differ is using `less` in this rather unconventional manner, I think it's worth fixing in asm-differ. One simple solution is to simply unset the `LESS` environment variable from within asm-differ, or looking for an option in the `less` man page to disable the -F behavior.

**Comment by simonlindholm** [comment]
Totally agreed! I made it pass -+F, -+X to disable those specific settings but leave other parts of $LESS intact.

**Comment by mid-kid** [comment]
Thanks a lot!
