### ISSUE TITLE
Update --stop-jr-ra function to support powerpc

### ISSUE THREAD

**Issue by mkst** [simonlindholm/asm-differ#115]
Mentioned here: https://github.com/decompme/decomp.me/issues/420 (check for `blr`)

**Comment by simonlindholm** [comment]
but we do check for blr: https://github.com/simonlindholm/asm-differ/blob/247994f34820afc2ed7e173427caad6199c4b666/diff.py#L1672

**Comment by mkst** [comment]
Lol, closing cos I cannot read.
