### ISSUE TITLE
Match reported incorrectly (arm32)

### ISSUE THREAD

**Issue by StanHash** [simonlindholm/asm-differ#80]
https://github.com/decompme/decomp.me/issues/394#issue-1149198288
I've been told I should report this here. Basically I'm told the output matches the input 100% while it still differs in exactly one spot.
I assume it is an issue with score computation only as it does seem to recognize the difference otherwise.

**Comment by simonlindholm** [comment]
Pushed an untested fix for this: b8907ddfc7d7d9433a48aa11a4516dcb2a247159. (I don't have a good test env set up atm.)

**Comment by ethteck** [comment]
Confirmed to be fixed! cc @StanHash

**Comment by StanHash** [comment]
nice!
