### ISSUE TITLE
Line numbers break with mwcceppc dwarf-2

### ISSUE THREAD

**Issue by SeekyCt** [simonlindholm/asm-differ#94]
When codewarrior is passed the `-sym dwarf-2` flag, a full path is output for the source file name, which includes a colon as part of the drive name and therefore breaks this regex https://github.com/simonlindholm/asm-differ/blob/b0ef0c5bf47573c5b1cb76b1627c834d806815e1/diff.py#L1958

Would allowing colons here break other things?

**Comment by simonlindholm** [comment]
I think it should be fine to allow.

**Comment by SeekyCt** [comment]
Cool, thanks
